---
title: "SheffieldR : Quarto for Slides"
author:
  - name: Neil Shephard
    orcid: 0000-0001-8301-6857
    email: n.shephard@sheffield.ac.uk
    affiliations: RSE, University of Sheffield
from: markdown+emoji
format:
  clean-revealjs:
    incremental: false
    slide-number: true
    show-slide-number: speaker
    auto-stretch: false
    # embed-resources: true
    # standalone: true
revealjs-plugins:
  - confetti
footer: "**Slides** : [**ns-rse.github.io/SheffieldR-quarto-for-slides**](https://ns-rse.github.io/SheffieldR-quarto-for-slides)"
project:
  preview:
    port: 7864
    host: localhost
    watch-inputs: true

---

## Slides

{{< qrcode https://ns-rse.github.io/SheffieldR-quarto-for-slides >}}


::: {.notes}
:::

## Overview

+ Background
+ Markdown
+ Using a template
+ Writing slides
+ Publishing

::: {.notes}
I thought it might be useful to cover a bit of history with regards to the philosophy that underpins Quarto, then cover
briefly the Markdown language which underpins writing slides before introducing the Template which is available to
kick-start this process.

Then I'm hoping to show how to write slides and also publish them using [GitHub Pages](https://pages.github.com/).

:::

## Background

+ _Literate Programming_
+ [Sweave](https://web.archive.org/web/20100130021808/http://www.statistik.lmu.de/~leisch/Sweave/)^[[Leisch F. (2002a)](http://www.ci.tuwien.ac.at/
~leisch/Sweave); [Leisch F (2002b)](https://journal.r-project.org/articles/RN-2002-025/); [Leisch F (2003)](https://journal.r-project.org/articles/RN-2003-013/)]
+ [RMarkdown](https://rmarkdown.rstudio.com/)^[[R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)]

. . .

+ :tada: [Quarto](https://quarto.org) :tada:

::: {.notes}
Quarto has a long pedigree
:::

## Markdown

+ Simple markup language.
+ Separate content from style.
+ Write in ASCII plain text.
+ Simple to version control.

::: {.notes}
Quarto uses its own dialect of Markdown which is a relatively simple markup language. There are lots of markup languages
such as HTML, LaTeX, RMarkdown, Restructured Text and many more.

Markup languages differ from Word Processor software such as Microsoft Word and Google Docs as they separate content,
what you are writing, from the style, which is how it looks because you write in ASCII plain text and adorn the text
with markers which indicate what it should look like and then apply themes to say what certain features should look
like.

Plain text files have the advantage that they are simple to keep under version control which also means they are easy to
work on collaboratively using tools such as GitHub or GitLab.
:::


## Basic Markdown

+ `**Bold**` : **Bold**
+ `_Italics_` : _Italics_
:::: {.columns}
::: {.column width="50%"}
``` {markdown}
**Bold**
```
:::
::: {.column width="50%"}
:::
::::

## Quarto RevealJS Template

[Quarto RevealJS Template](https://github.com/ns-rse/quarto-revealjs-template) includes...

+ Sample slides with many examples.
+ GitHub workflow/action to publish pages.
+ Instructions on usage.
+ Make a copy to your account.
+ Change settings _Settings > Actions > Workflow Permissions > Read and write_

::: {.notes}

:::

## Using Quarto RevealJS Template


+ GitHub account (ideally with `@sheffield.ac.uk`)
+ Go to [Quarto RevealJS Template](https://github.com/ns-rse/quarto-revealjs-template)
+ Make a copy to your account & rename to `my_first_quarto_slides`.
+ Change settings _Settings > Actions > Workflow Permissions > Read and write_

::: {.notes}

:::


## Cloning

+ Need files locally.
+ Git lingua this means cloning.
+ RStudio _File > New Project > Version Control > Git_.
+ Paste URL `https://github.com/<username>/my_first_quarto_slides`.
::: {.notes}
:::


## Initial Publish

+ `quarto publish`
+ Creates a special branch `gh-pages` which holds HTML.
+ Pushes branch to GitHub.
+ View slides at
  [https://<username>.github.io/my_first_quarto_slides/](https://ns-rse.github.io/my_first_quarto_slides/)

::: {.notes}
:::

## `_quarto.yaml`

+ Configuration file for slides.
+ Define key metadata (Author, Email, [ORCiD](https://orcid.org))
+ Set common slide properties (e.g. `incremental`, `chalkboard`)
+ Define Footer

::: {.notes}
:::

## `index.qmd`

+ _Now_ you can write your slides!

::: {.notes}
:::

## Images

::: {.notes}
:::

## Links

::: {.notes}
:::

## Speaker Notes

::: {.notes}
A nice feature of RevealJS common to many slide presentation software is the ability to add speaker notes to the bottom
of every slide.
:::

## Previewing

::: {.notes}
Quarto will render your slides locally and start a web-server for you to view the pages _before_ you push them to GitHub.
:::

## Commit and Push

::: {.notes}
:::

## Extensions

+ Lots of [extensions](https://quarto.org/docs/extensions/).
+ Add functionality.
+ Need installing to repository locally _and_ adding to GitHub Action.

::: {.notes}
:::

## Linting with `pre-commit`

+ Includes [pre-commit](https://pre-commit.com) hook to lint Markdown.
+ Ensures consistent style used.
+ [markdownlint-cli2]().
+ Configuration via `.markdownlint-cli2.yaml`.
+ Automatically fixes mistakes where possible.
